name: Run build
on: [ workflow_call, workflow_dispatch ]

jobs:

  linux:
    name: Build targets on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install conan

      - run: conan install packages/openssl3 --install-folder build/openssl3/linuxX64 --build=missing --profile profiles/linuxX64
      - run: conan install packages/openssl3 --install-folder build/openssl3/linuxArm64 --build=missing --profile profiles/linuxArm64

      - uses: actions/upload-artifact@v3
        with:
          name: openssl3-linux
          path: build/openssl3/*/lib/*.*

  windows:
    if: false
    name: Build targets on windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install conan

      - run: conan install packages/openssl3 --install-folder build/openssl3/mingwX64 --build=missing --profile profiles/mingwX64

      - uses: actions/upload-artifact@v3
        with:
          name: openssl3-windows
          path: build/openssl3/*/lib/*.*

  macos:
    if: false
    name: Build targets on macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install conan

      - run: conan install packages/openssl3 --install-folder build/openssl3/macosArm64 --build=missing --profile profiles/macosArm64
      - run: conan install packages/openssl3 --install-folder build/openssl3/macosX64 --build=missing --profile profiles/macosX64
      - run: conan install packages/openssl3 --install-folder build/openssl3/iosArm64 --build=missing --profile profiles/iosArm64
      - run: conan install packages/openssl3 --install-folder build/openssl3/iosArm32 --build=missing --profile profiles/iosArm32
      - run: conan install packages/openssl3 --install-folder build/openssl3/iosSimulatorArm64 --build=missing --profile profiles/iosSimulatorArm64
      - run: conan install packages/openssl3 --install-folder build/openssl3/iosSimulatorX64 --build=missing --profile profiles/iosSimulatorX64

      - uses: actions/upload-artifact@v3
        with:
          name: openssl3-macos
          path: build/openssl3/*/lib/*.*
