name: Run build
on: [ workflow_call, workflow_dispatch ]

jobs:

  linux:
    name: Build targets on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install conan

      - run: conan install packages/openssl3 --install-folder build/openssl3/linux-x64 --build=missing --profile profiles/linux-x64

      - uses: actions/upload-artifact@v3
        with:
          name: openssl3
          path: build/openssl3/*/lib/*.*

  windows:
    name: Build targets on windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install conan

      - run: conan install packages/openssl3 --install-folder build/openssl3/mingw-x64 --build=missing --profile profiles/mingw-x64

      - uses: actions/upload-artifact@v3
        with:
          name: openssl3
          path: build/openssl3/*/lib/*.*

  macos:
    name: Build targets on macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install conan

      - run: conan install packages/openssl3 --install-folder build/openssl3/macos-arm64 --build=missing --profile profiles/macos-arm64
      - run: conan install packages/openssl3 --install-folder build/openssl3/macos-x64 --build=missing --profile profiles/macos-x64

      - run: conan install packages/openssl3 --install-folder build/openssl3/ios-device-arm64 --build=missing --profile profiles/ios-device-arm64

      - run: conan install packages/openssl3 --install-folder build/openssl3/ios-simulator-arm64 --build=missing --profile profiles/ios-simulator-arm64
      - run: conan install packages/openssl3 --install-folder build/openssl3/ios-simulator-x64 --build=missing --profile profiles/ios-simulator-x64

      - uses: actions/upload-artifact@v3
        with:
          name: openssl3
          path: build/openssl3/*/lib/*.*
