name: Run build
on: [ workflow_call, workflow_dispatch ]

jobs:
  macos:
    name: Build darwin targets
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        profile: [
          macosArm64, macosX64,
          iosArm64, iosArm32,
          iosSimulatorArm64, iosSimulatorX64
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install conan
      - run: conan install packages/openssl3 --install-folder packages/openssl3/build/${{ matrix.profile }} --build=missing --profile profiles/${{ matrix.profile }}
      - uses: actions/upload-artifact@v3
        with:
          name: openssl3-${{ matrix.profile }}
          path: packages/openssl3/build/${{ matrix.profile }}/lib/*.a
