name: Run build
on: [ workflow_call, workflow_dispatch ]

jobs:
  openssl3:
    name: Build openssl3
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
        target: [ macos-x64, macos-arm64, ios-device-arm64, ios-simulator-arm64, ios-simulator-x64 ]
        include:
          - os: ubuntu-20.04
            target: linux-x64
          - os: windows-latest
            target: mingw-x64
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install conan

      - run: conan install packages/openssl3 --install-folder build/openssl3/${{ matrix.target }} --build=missing --profile profiles/${{ matrix.target }} -o openssl:shared=False
      - run: conan install packages/openssl3 --install-folder build/openssl3/${{ matrix.target }} --build=missing --profile profiles/${{ matrix.target }} -o openssl:shared=True

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: openssl3-all
          if-no-files-found: error
          path: |
            build/openssl3/*/lib/dynamic/*
            build/openssl3/*/lib/static/*
            build/openssl3/*/include/openssl/*

#      - uses: actions/upload-artifact@v3
#        if: always()
#        with:
#          name: openssl3-${{ matrix.target }}
#          if-no-files-found: error
#          path: |
#            build/openssl3/${{ matrix.target }}/lib/dynamic/*
#            build/openssl3/${{ matrix.target }}/lib/static/*
#            build/openssl3/${{ matrix.target }}/include/openssl/*
